### ISSUE TITLE
Catch three geocaches in three different cities

### ISSUE THREAD

**Issue by alignan** [alignan/things-to-do#5]

**Comment by lalifala** [comment]
Happy to help with Geo-caching!

**Comment by alignan** [comment]
@lalifala let's grab a beer and go catch some after I return from holidays 👍

**Comment by lalifala** [comment]
@alignan that sounds good!

**Comment by alignan** [comment]
https://github.com/alignan/things-to-do/commit/a0fc7b288fde92c515e1b18054003963121e923e
